// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package genproto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaultServiceClient interface {
	GetCatalog(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (VaultService_GetCatalogClient, error)
	GetItem(ctx context.Context, in *SelectItem, opts ...grpc.CallOption) (*ItemResponse, error)
	DeleteItem(ctx context.Context, in *SelectItem, opts ...grpc.CallOption) (*empty.Empty, error)
	AddItem(ctx context.Context, in *SetItem, opts ...grpc.CallOption) (*ItemResponse, error)
	UpdateItem(ctx context.Context, in *SetItem, opts ...grpc.CallOption) (*ItemResponse, error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) GetCatalog(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (VaultService_GetCatalogClient, error) {
	stream, err := c.cc.NewStream(ctx, &VaultService_ServiceDesc.Streams[0], "/VaultService/GetCatalog", opts...)
	if err != nil {
		return nil, err
	}
	x := &vaultServiceGetCatalogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VaultService_GetCatalogClient interface {
	Recv() (*CatalogResult, error)
	grpc.ClientStream
}

type vaultServiceGetCatalogClient struct {
	grpc.ClientStream
}

func (x *vaultServiceGetCatalogClient) Recv() (*CatalogResult, error) {
	m := new(CatalogResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vaultServiceClient) GetItem(ctx context.Context, in *SelectItem, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/VaultService/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) DeleteItem(ctx context.Context, in *SelectItem, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/VaultService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) AddItem(ctx context.Context, in *SetItem, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/VaultService/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) UpdateItem(ctx context.Context, in *SetItem, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/VaultService/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
// All implementations must embed UnimplementedVaultServiceServer
// for forward compatibility
type VaultServiceServer interface {
	GetCatalog(*empty.Empty, VaultService_GetCatalogServer) error
	GetItem(context.Context, *SelectItem) (*ItemResponse, error)
	DeleteItem(context.Context, *SelectItem) (*empty.Empty, error)
	AddItem(context.Context, *SetItem) (*ItemResponse, error)
	UpdateItem(context.Context, *SetItem) (*ItemResponse, error)
	mustEmbedUnimplementedVaultServiceServer()
}

// UnimplementedVaultServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVaultServiceServer struct {
}

func (UnimplementedVaultServiceServer) GetCatalog(*empty.Empty, VaultService_GetCatalogServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCatalog not implemented")
}
func (UnimplementedVaultServiceServer) GetItem(context.Context, *SelectItem) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedVaultServiceServer) DeleteItem(context.Context, *SelectItem) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedVaultServiceServer) AddItem(context.Context, *SetItem) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (UnimplementedVaultServiceServer) UpdateItem(context.Context, *SetItem) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedVaultServiceServer) mustEmbedUnimplementedVaultServiceServer() {}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_GetCatalog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VaultServiceServer).GetCatalog(m, &vaultServiceGetCatalogServer{stream})
}

type VaultService_GetCatalogServer interface {
	Send(*CatalogResult) error
	grpc.ServerStream
}

type vaultServiceGetCatalogServer struct {
	grpc.ServerStream
}

func (x *vaultServiceGetCatalogServer) Send(m *CatalogResult) error {
	return x.ServerStream.SendMsg(m)
}

func _VaultService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VaultService/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).GetItem(ctx, req.(*SelectItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VaultService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).DeleteItem(ctx, req.(*SelectItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VaultService/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).AddItem(ctx, req.(*SetItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VaultService/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).UpdateItem(ctx, req.(*SetItem))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _VaultService_GetItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _VaultService_DeleteItem_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _VaultService_AddItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _VaultService_UpdateItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCatalog",
			Handler:       _VaultService_GetCatalog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vault.proto",
}
